version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: tdmb:latest
    container_name: movie_app
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - MAIL_USERNAME=${MAIL_ACCOUNT}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - REDIRECT_URI=${REDIRECT_URI}
      - CLOUDINARY_URL=${CLOUDINARY_URL}