name: CI/CD Pipeline Production

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  statuses: write

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      MAIL_ACCOUNT: ${{ secrets.MAIL_ACCOUNT }}
      MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
      REDIS_HOST: ${{ secrets.REDIS_HOST }}
      REDIS_PORT: ${{ secrets.REDIS_PORT }}
      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      REDIRECT_URI: ${{ secrets.REDIRECT_URI }}
      CLOUDINARY_URL: ${{ secrets.CLOUDINARY_URL }}

    steps:
      # Checkout the source code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK 17 for the build
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      # Build the project with Maven
      - name: Build with Maven
        run: mvn clean install

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker image
      - name: Build and Push Docker Image
        run: |
          docker build -t hcdman/tmdb-back-end:1.0 .
          docker push hcdman/tmdb-back-end:1.0

  deploy:
    name: Deploy Docker Image to Azure Web App
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: none
    environment:
      name: 'Production'

    steps:
      # Deploy the Docker image to Azure Web App
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: tmdb-backend
          slot-name: production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: hcdman/tmdb-back-end:1.0

      # Display the deployment URL
      - name: Set Deployment URL
        run: echo "webapp-url=https://tmdb-backend-cqbrdcdkfsbqh0gw.japaneast-01.azurewebsites.net" >> $GITHUB_ENV

    outputs:
      webapp-url: https://tmdb-backend-cqbrdcdkfsbqh0gw.japaneast-01.azurewebsites.net
